name: DOODS2-new
version: '1'
slug: doods2-new
url: https://github.com/snowzach/hassio-addons/tree/master/doods2-new
description: DOODS V1 Object Detection API - New
webui: http://[HOST]:[PORT:8080]
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: services
map:
  - share
usb: true
options: 
  logging:
    level: info
schema:
  logging:
    level: str?
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: DOODS2 port
